package ai.mobi.softconstraints

val fullAdderConstraintsProblem = vcsp("full_adder")
    .variable("u").domain("0", "1")
    .variable("v").domain("0", "1")
    .variable("w").domain("0", "1")
    .variable("y").domain("0", "1")
    .variable("a1").domain("G", "B")
    .variable("a2").domain("G", "B")
    .variable("e1").domain("G", "B")
    .variable("e2").domain("G", "B")
    .variable("o1").domain("G", "B")

    .constraint("fa1").scope("w", "y", "a1")
    .assignment("0", "0", "G").value(.99f)
    .assignment("1", "1", "G").value(.99f)
    .assignment("0", "0", "B").value(.01f)
    .assignment("0", "1", "B").value(.01f)
    .assignment("1", "0", "B").value(.01f)
    .assignment("1", "1", "B").value(.01f)

    .constraint("fa2").scope("u", "v", "a2")
    .assignment("0", "0", "G").value(.99f)
    .assignment("1", "1", "G").value(.99f)
    .assignment("0", "0", "B").value(.01f)
    .assignment("0", "1", "B").value(.01f)
    .assignment("1", "0", "B").value(.01f)
    .assignment("1", "1", "B").value(.01f)

    .constraint("fe1").scope("u", "y", "e1")
    .assignment("1", "0", "G").value(.95f)
    .assignment("0", "1", "G").value(.95f)
    .assignment("0", "0", "B").value(.05f)
    .assignment("0", "1", "B").value(.05f)
    .assignment("1", "0", "B").value(.05f)
    .assignment("1", "1", "B").value(.05f)

    .constraint("fe2").scope("u", "e2")
    .assignment("0", "G").value(.95f)
    .assignment("0", "B").value(.05f)
    .assignment("1", "B").value(.05f)

    .constraint("fo1").scope("v", "w", "o1")
    .assignment("0", "0", "G").value(.95f)
    .assignment("0", "0", "B").value(.05f)
    .assignment("0", "1", "B").value(.05f)
    .assignment("1", "0", "B").value(.05f)
    .assignment("1", "1", "B").value(.05f)

    .build()