package ai.mobi.softconstraints

val fullAdderConstraintsProblem = vcsp("full_adder")
    .variable("a1").domain("G", "B")
    .variable("a2").domain("G", "B")
    .variable("e1").domain("G", "B")
    .variable("e2").domain("G", "B")
    .variable("o1").domain("G", "B")
    .variable("u").domain("0", "1")
    .variable("v").domain("0", "1")
    .variable("w").domain("0", "1")
    .variable("y").domain("0", "1")

    .constraint("fa1").scope("a1", "w", "y")
    .assignment("G", "0", "0").value(.99f)
    .assignment("G", "1", "1").value(.99f)
    .assignment("B", "0", "0").value(.01f)
    .assignment("B", "0", "1").value(.01f)
    .assignment("B", "1", "0").value(.01f)
    .assignment("B", "1", "1").value(.01f)

    .constraint("fa2").scope("a2", "u", "v")
    .assignment("G", "0", "0").value(.99f)
    .assignment("G", "1", "1").value(.99f)
    .assignment("B", "0", "0").value(.01f)
    .assignment("B", "0", "1").value(.01f)
    .assignment("B", "1", "0").value(.01f)
    .assignment("B", "1", "1").value(.01f)

    .constraint("fe1").scope("e1", "u", "y")
    .assignment("G", "1", "0").value(.95f)
    .assignment("G", "0", "1").value(.95f)
    .assignment("B", "0", "0").value(.05f)
    .assignment("B", "0", "1").value(.05f)
    .assignment("B", "1", "0").value(.05f)
    .assignment("B", "1", "1").value(.05f)

    .constraint("fe2").scope("e2", "u")
    .assignment("G", "0").value(.95f)
    .assignment("B", "0").value(.05f)
    .assignment("B", "1").value(.05f)

    .constraint("fo1").scope("o1", "v", "w")
    .assignment("G", "0", "0").value(.95f)
    .assignment("B", "0", "0").value(.05f)
    .assignment("B", "0", "1").value(.05f)
    .assignment("B", "1", "0").value(.05f)
    .assignment("B", "1", "1").value(.05f)

    .build()